x-yaml-anchors:  # create anchors "&something" that can be referenced using "*something"
  x11-base: &x11-base
    extends:
      file: docker/common.yaml
      service: x11_base


services:
  compile:
    extends:
      file: docker/common.yaml
      service: base
    command: catkin build

  bash:
    <<: *x11-base
    command: bash --rcfile /etc/bash.bashrc

  simu:
    <<: *x11-base
    environment:
      ROBOT_INITIAL_POSE: -x -10 -y -1 -Y -2.1
    command: roslaunch path_following_demo path_following.launch demo:=simu

  debug_path_following:
    <<: *x11-base
    command: >-
      roslaunch path_following_demo path_following_algo.launch --no-summary
        config_dir:=$$WORKSPACE/src/demos/path_following/config
        output:=screen
        ns:=/path_following

