x-yaml-anchors:  # create anchors "&something" that can be referenced using "*something"
  x11-base: &x11-base
    extends:
      file: docker/common.yaml
      service: x11_base


services:
  compile:
    extends:
      file: docker/common.yaml
      service: base
    command: catkin build

  bash:
    <<: *x11-base
    command: bash --rcfile /etc/bash.bashrc

  simu:
    <<: *x11-base
    command: roslaunch path_following_demo path_following.launch demo:=simu
